version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Frank-Mayer"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    reviewers:
      - "Frank-Mayer"
